version: '3.8'

services:
  globalsolutionjava:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - oracle-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
      SPRING_DATASOURCE_USERNAME: RM552648  
      SPRING_DATASOURCE_PASSWORD: fiap24
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - "1521:1521"
    environment:
      ORACLE_ALLOW_REMOTE: "true"
      ORACLE_PASSWORD: fiap24
    volumes:
      - oracle-data:/u01/app/oracle
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G

networks:
  app-network:
    driver: bridge

volumes:
  oracle-data: